### ISSUE TITLE
how much it cost if we use gtp4

### ISSUE THREAD

**Issue by pabl-o-ce** [melodysdreamj/WizardVicunaLM#2]
Love the idea and the project you made

My question is how much will cost if we can use gpt4

Do you think is possible to have an idea of that cost?

So I can share the token but having a knowledge of how much it will cost

**Comment by melodysdreamj** [comment]
I spent 250$ while expanding the dataset of the Wizard. GPT4 32K is 60 times more expensive than chatgpt3.5, so I think you'll need about 15000$ to tune it.
