### ISSUE TITLE
finetune code and hyperparameters

### ISSUE THREAD

**Issue by ehartford** [melodysdreamj/WizardVicunaLM#6]
Can I please have the fine tune code and hyperparameters so I can reproduce it?  or did you just use Vicuna's code?

**Comment by melodysdreamj** [comment]
I used the code suggested by Vicuna, which can be found [here ](https://github.com/lm-sys/FastChat/blob/main/scripts/train_vicuna_13b.sh)

**Comment by ehartford** [comment]
Thank you! did you make any changes, or you used it exactly like that?

**Comment by melodysdreamj** [comment]
Yes I used the hyperparameters over there, thanks :)
